# Generated by Django 5.1.4 on 2024-12-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('vegetetion_predominance', models.CharField(blank=True, max_length=100)),
                ('fauna_predominance', models.CharField(blank=True, max_length=100)),
                ('area', models.FloatField(blank=True, null=True)),
                ('state_vegetetion', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
