# Generated by Django 5.1.4 on 2024-12-11 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biomes', '0001_initial'),
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomemodel',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='picture.picturemodel'),
        ),
    ]
