markdown_extensions:
- codehilite:
    guess_lang: false
    pygments_style: monokai
- toc


nav:
- Inicio: index.md
- API:
  - Biomes: api/Biomes/index.md
  - comments: api/comments/index.md
  - heart: api/heart/index.md
  - notification: api/notification/index.md
  - picture: api/picture/index.md
  - reports: api/reports/index.md
  - token: api/token/index.md
  - users: api/users/index.md
  - utils: api/utils/index.md


plugins:
- search
- gen-files:
    scripts:
    - core/management/commands/gen_docs.py
- mkdocstrings


site_name: "EcoVista Documentação"


theme:
  font:
    code: Roboto Mono
    text: Roboto
  name: material
  palette:
    accent: light-green
    primary: green

extra_css:
  - /styles/mkdocs.css
